### ISSUE TITLE
Changing binsize to more than 100

### ISSUE THREAD

**Issue by MargoSambor** [YuliaRubanova/Trackature#9]
I've been altering the bin size for the test example that is presented in the usage section of the README (not using simulated input). I changed 100 to a variable in the make_counts.sh, compute_mutational_signatures.R and helper_functions.R scripts but for bin sizes larger that 100 I am getting exposures larger than 100 (see plot attached, this is for bin size 150). Do you have any idea why this might be happening?
![exposure_binsize_150](https://user-images.githubusercontent.com/29729358/60766732-01662f00-a0a6-11e9-8048-c21e8d605f88.png)

**Comment by YuliaRubanova** [comment]
Hi,
I have added the bin_size parameter to make_counts.sh and header.R. Please check out the latest version of the code.

To answer you question, I think the issue is in the call of plotting functions (`plot_signatures` or `plot_signatures_real_scale` in `compute_mutational_signatures.R`).  Signature activities range between 0 and 1. For the sake of plotting, we covert them into a percentage by multiplying them by 100 `plot_signatures(mixtures*100, ...)`. 

Since bin size is also 100, you might have replaced the multiplication to `plot_signatures(mixtures*bin_size, ...)`. Your issue should be resolved if you replace it by `plot_signatures(mixtures*100, ...)`

**Comment by MargoSambor** [comment]
Hey Yulia,


Thank you so much for the commit and for your help!

I've noticed that in the paper in bioarchive figure 1 x axis is "Cancer
cell fraction" but in the test example which is on github the resulting pdf
has an x axis "average numer of mutant alleles per cancer cell" (the pdf is
called "LAML_example_onlyKnownSignatures.pdf" in
results_signature_trajectories/LAML/example).
And for the example in github the x axis values go from 2.1 (smth like
that) to 0, not from 1 to 0 - so that means these are not corrected by copy
number?

How could I generate a plot which is exactly like the figure 1 in the paper
(with cancer cell fraction on the x axis)?

Thank you for your help. sorry for bothering you.

Best wishes,
Margarita

вт, 9 июл. 2019 г. в 16:13, Yulia Rubanova <notifications@github.com>:
